schemes:
  onedark: &onedark
    primary:
      foreground: "#abb2bf"
      background: "#1e2127"

    normal:
      black: "#1e2127"
      red: "#e06c75"
      green: "#98c379"
      yellow: "#d19a66"
      blue: "#61afef"
      magenta: "#c678dd"
      cyan: "#56b6c2"
      white: "#abb2bf"

    bright:
      black: "#5c6370"
      red: "#e06c75"
      green: "#98c379"
      yellow: "#d19a66"
      blue: "#61afef"
      magenta: "#c678dd"
      cyan: "#56b6c2"
      white: "#ffffff"

colors: *onedark
